services:
    mongo:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        ports:
            - "27017:27017"

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/

    database:
        container_name: database
        image: mysql/mysql-server:8.0.31
        working_dir: /database
        
        ports:
            - "33333:3306"
            
        expose:
            - "33333"
        
        environment:
            MYSQL_DATABASE: imse
            MYSQL_PASSWORD: information
            MYSQL_ROOT_PASSWORD: information
            MYSQL_USER: root

    backend:
        container_name: backend
        working_dir: /backend
        image: imse/backend

        depends_on:
            - database
            - mongo

        ports: 
            - "5000:8080"

        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/imse
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=information
            - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/imse?authSource=admin
            
    frontend:
        container_name: frontend
        working_dir: /frontend
        image: imse/frontend
        
        depends_on:
            - backend
        
        ports: 
            - "80:80"
            - "443:443"

        environment:
            - API_URL=http://localhost:5000
            #- API_URL=http://backend:8080
