services:
    database:
        container_name: database
        image: mysql/mysql-server:8.0.31
        working_dir: /database
        
        ports:
            - "33333:3306"
            
        expose:
            - "33333"
        
        environment:
            MYSQL_DATABASE: imse
            MYSQL_PASSWORD: information
            MYSQL_ROOT_PASSWORD: information
            MYSQL_USER: root

    backend:
        container_name: backend
        working_dir: /backend
        image: imse/backend

        depends_on:
            - database

        ports: 
            - "5000:8080"

        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/imse
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=information
            
    frontend:
        container_name: frontend
        working_dir: /frontend
        image: imse/frontend
        
        depends_on:
            - backend
        
        ports: 
            - "80:80"

        environment:
            - API_URL=http://localhost:5000
            #- API_URL=http://backend:8080
