spring:
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  security:
    user:
      name: imse
      password: imseimse

  data:
    jdbc:
      repositories:
        enabled: false
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:example@localhost:27017/imse?authSource=admin}
      database: imse

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              #MongoTemplate: DEBUG